# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/pettyflow/v1/float_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'proto/pettyflow/v1/float_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&proto/pettyflow/v1/float_service.proto\x12\x0cpettyflow.v1\"\x81\x01\n\x04\x46und\x12\x0f\n\x07\x66und_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x14\n\x0c\x63ustodian_id\x18\x05 \x01(\t\x12\x1f\n\x17\x61vailable_amount_scaled\x18\x06 \x01(\x03\"u\n\x10\x43ustodianBalance\x12\x0f\n\x07\x66und_id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63ustodian_id\x18\x03 \x01(\t\x12\x10\n\x08\x63urrency\x18\x04 \x01(\t\x12\x15\n\ramount_scaled\x18\x05 \x01(\x03\"{\n\x11\x43reateFundRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63urrency\x18\x03 \x01(\t\x12\x14\n\x0c\x63ustodian_id\x18\x04 \x01(\t\x12\x1d\n\x15initial_amount_scaled\x18\x05 \x01(\x03\"g\n\x14\x41llocateFloatRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0f\n\x07\x66und_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63ustodian_id\x18\x03 \x01(\t\x12\x15\n\ramount_scaled\x18\x04 \x01(\x03\"k\n\x18IssueDisbursementRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0f\n\x07\x66und_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63ustodian_id\x18\x03 \x01(\t\x12\x15\n\ramount_scaled\x18\x04 \x01(\x03\"V\n\x1aGetCustodianBalanceRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\x0f\n\x07\x66und_id\x18\x02 \x01(\t\x12\x14\n\x0c\x63ustodian_id\x18\x03 \x01(\t2\xe4\x02\n\x0c\x46loatService\x12\x41\n\nCreateFund\x12\x1f.pettyflow.v1.CreateFundRequest\x1a\x12.pettyflow.v1.Fund\x12S\n\rAllocateFloat\x12\".pettyflow.v1.AllocateFloatRequest\x1a\x1e.pettyflow.v1.CustodianBalance\x12[\n\x11IssueDisbursement\x12&.pettyflow.v1.IssueDisbursementRequest\x1a\x1e.pettyflow.v1.CustodianBalance\x12_\n\x13GetCustodianBalance\x12(.pettyflow.v1.GetCustodianBalanceRequest\x1a\x1e.pettyflow.v1.CustodianBalanceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.pettyflow.v1.float_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FUND']._serialized_start=57
  _globals['_FUND']._serialized_end=186
  _globals['_CUSTODIANBALANCE']._serialized_start=188
  _globals['_CUSTODIANBALANCE']._serialized_end=305
  _globals['_CREATEFUNDREQUEST']._serialized_start=307
  _globals['_CREATEFUNDREQUEST']._serialized_end=430
  _globals['_ALLOCATEFLOATREQUEST']._serialized_start=432
  _globals['_ALLOCATEFLOATREQUEST']._serialized_end=535
  _globals['_ISSUEDISBURSEMENTREQUEST']._serialized_start=537
  _globals['_ISSUEDISBURSEMENTREQUEST']._serialized_end=644
  _globals['_GETCUSTODIANBALANCEREQUEST']._serialized_start=646
  _globals['_GETCUSTODIANBALANCEREQUEST']._serialized_end=732
  _globals['_FLOATSERVICE']._serialized_start=735
  _globals['_FLOATSERVICE']._serialized_end=1091
# @@protoc_insertion_point(module_scope)
