# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.pettyflow.v1 import float_service_pb2 as proto_dot_pettyflow_dot_v1_dot_float__service__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/pettyflow/v1/float_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FloatServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateFund = channel.unary_unary(
                '/pettyflow.v1.FloatService/CreateFund',
                request_serializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.CreateFundRequest.SerializeToString,
                response_deserializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.Fund.FromString,
                _registered_method=True)
        self.AllocateFloat = channel.unary_unary(
                '/pettyflow.v1.FloatService/AllocateFloat',
                request_serializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.AllocateFloatRequest.SerializeToString,
                response_deserializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.CustodianBalance.FromString,
                _registered_method=True)
        self.IssueDisbursement = channel.unary_unary(
                '/pettyflow.v1.FloatService/IssueDisbursement',
                request_serializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.IssueDisbursementRequest.SerializeToString,
                response_deserializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.CustodianBalance.FromString,
                _registered_method=True)
        self.GetCustodianBalance = channel.unary_unary(
                '/pettyflow.v1.FloatService/GetCustodianBalance',
                request_serializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.GetCustodianBalanceRequest.SerializeToString,
                response_deserializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.CustodianBalance.FromString,
                _registered_method=True)


class FloatServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateFund(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AllocateFloat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IssueDisbursement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCustodianBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FloatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateFund': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFund,
                    request_deserializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.CreateFundRequest.FromString,
                    response_serializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.Fund.SerializeToString,
            ),
            'AllocateFloat': grpc.unary_unary_rpc_method_handler(
                    servicer.AllocateFloat,
                    request_deserializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.AllocateFloatRequest.FromString,
                    response_serializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.CustodianBalance.SerializeToString,
            ),
            'IssueDisbursement': grpc.unary_unary_rpc_method_handler(
                    servicer.IssueDisbursement,
                    request_deserializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.IssueDisbursementRequest.FromString,
                    response_serializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.CustodianBalance.SerializeToString,
            ),
            'GetCustodianBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCustodianBalance,
                    request_deserializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.GetCustodianBalanceRequest.FromString,
                    response_serializer=proto_dot_pettyflow_dot_v1_dot_float__service__pb2.CustodianBalance.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pettyflow.v1.FloatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pettyflow.v1.FloatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FloatService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateFund(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pettyflow.v1.FloatService/CreateFund',
            proto_dot_pettyflow_dot_v1_dot_float__service__pb2.CreateFundRequest.SerializeToString,
            proto_dot_pettyflow_dot_v1_dot_float__service__pb2.Fund.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AllocateFloat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pettyflow.v1.FloatService/AllocateFloat',
            proto_dot_pettyflow_dot_v1_dot_float__service__pb2.AllocateFloatRequest.SerializeToString,
            proto_dot_pettyflow_dot_v1_dot_float__service__pb2.CustodianBalance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IssueDisbursement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pettyflow.v1.FloatService/IssueDisbursement',
            proto_dot_pettyflow_dot_v1_dot_float__service__pb2.IssueDisbursementRequest.SerializeToString,
            proto_dot_pettyflow_dot_v1_dot_float__service__pb2.CustodianBalance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCustodianBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pettyflow.v1.FloatService/GetCustodianBalance',
            proto_dot_pettyflow_dot_v1_dot_float__service__pb2.GetCustodianBalanceRequest.SerializeToString,
            proto_dot_pettyflow_dot_v1_dot_float__service__pb2.CustodianBalance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
